# Generated by Django 4.2.30 on 2026-09-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackentry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
