# Generated by Django 4.2.30 on 2026-07-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.CharField(help_text="e.g. 'April 2026'", max_length=20)),
                ('total_school_days', models.PositiveIntegerField()),
                ('days_present', models.PositiveIntegerField()),
                ('average_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('teacher_comments', models.TextField(blank=True)),
                ('report_card', models.FileField(blank=True, null=True, upload_to='documents/report_cards/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
