# Generated by Django 4.2.30 on 2026-07-30 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orphans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='orphan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='orphans.orphan'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
