# Generated by Django 4.2.30 on 2026-09-15 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orphans', '0004_orphan_monthly_fee'),
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text="e.g. 'September 2026'", max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='orphans.orphan')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_fee_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='schools.school')),
            ],
            options={
                'unique_together': {('orphan', 'month')},
            },
        ),
    ]
