# Generated by Django 4.2.30 on 2026-07-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_cnic', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('school_name_text', models.CharField(help_text='School name as typed on the form', max_length=200)),
                ('student_class', models.CharField(blank=True, max_length=20)),
                ('death_certificate', models.FileField(blank=True, null=True, upload_to='documents/death_certificates/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='documents/photos/')),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
