# Generated by Django 4.2.30 on 2026-09-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphan',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the child in years', null=True),
        ),
        migrations.AddField(
            model_name='orphan',
            name='is_currently_studying',
            field=models.BooleanField(default=True, help_text='False when guardian did not provide school/class'),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='school_name_text',
            field=models.CharField(blank=True, help_text='School name as typed on the form (optional)', max_length=200),
        ),
    ]
