# Generated by Django 4.2.30 on 2026-09-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0003_orphan_age_orphan_is_currently_studying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphan',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly fee set by Admin upon approval', max_digits=10),
        ),
    ]
