# Generated by Django 4.2.30 on 2026-09-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0004_orphan_monthly_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphan',
            name='b_form_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/b_forms/'),
        ),
        migrations.AddField(
            model_name='orphan',
            name='child_cnic',
            field=models.CharField(blank=True, help_text='Child CNIC or B-Form number', max_length=20),
        ),
    ]
