# Generated by Django 4.2.30 on 2026-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0005_orphan_b_form_document_orphan_child_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphan',
            name='school_phone',
            field=models.CharField(blank=True, help_text='School phone number', max_length=20),
        ),
    ]
