# Generated by Django 6.0.7 on 2026-09-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
