# Generated by Django 4.2.30 on 2026-09-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donation_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
